name: CI
on:
  push:
    paths-ignore:
      - ".vscode"
      - "*.md"
      - "LICENCE"

jobs:
  windows:
    name: Windows build on node ${{ matrix.node_version }}
    runs-on: windows-latest
    strategy:
      matrix:
        node_version: [12.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install packages
        run: npm install

      - name: Run build
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build/release Electron app
        uses: wixplosives/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GH_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

